# Generated by Django 4.0.1 on 2022-01-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_testmodel_alter_news_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
