# Generated by Django 4.0.1 on 2022-01-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
